### GET /todos
@host = http://localhost:5294


GET {{host}}/todos HTTP/1.1

### GET1 /todos/1
GET {{host}}/todos/3 HTTP/1.1


### POST /todos
@host = http://localhost:5294
@dueDate = 2026-06-14T00:00:00Z

POST {{host}}/todos HTTP/1.1
Content-Type: application/json

{
    "id": 3,
    "name": "New Todo",
    "dueDate": "{{dueDate}}",
    "isCompleted": false
}


### DELETE /todos/{id}
@host = http://localhost:5294
@id = 3

DELETE {{host}}/todos/{{id}}

